console.info("[SOCIETY-S-COBBLEMON] cobblemonFishingPool.js loaded");

global.cobblemonFishPool = [
    { pokemon: "squirtle", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "wartortle", weight: .75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "blastoise", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "psyduck", weight: 25, lvlRange: [5, 35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring'], waterTypes: ['fresh', 'river'] },
    { pokemon: "golduck", weight: 15, lvlRange: [15, 40], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer'], waterTypes: ['fresh', 'river'] },
    { pokemon: "poliwag", weight: 25, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring, summer'], waterTypes: ['fresh', 'river'] },
    { pokemon: "poliwhirl", weight: 10, lvlRange: [25, 40], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "tentacool", weight: 30, lvlRange: [10, 35], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "tentacruel", weight: 10, lvlRange: [30, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "chewtle", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh'] },
    { pokemon: "dreadnaw", weight: 5, lvlRange: [25, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh'] },
    { pokemon: "slowpoke", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "slowpoke", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh', 'river'], variant: ['galarian'] },
    { pokemon: "slowbro", weight: 5, lvlRange: [37, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "slowbro", weight: 5, lvlRange: [37, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['fresh', 'river'], variant: ['galarian'] },
    { pokemon: "seel", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean', 'river'] },
    { pokemon: "dewgong", weight: 5, lvlRange: [35, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean', 'river'] },
    { pokemon: "grimer", weight: 10, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "muk", weight: 5, lvlRange: [40, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "grimer", weight: 5, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['summer'], waterTypes: ['ocean', 'river', 'fresh'], variant: ['alolan'] },
    { pokemon: "muk", weight: 1, lvlRange: [40, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer'], waterTypes: ['ocean', 'river', 'fresh'], variant: ['alolan'] },
    { pokemon: "trubbish", weight: 5, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "garbodor", weight: 3, lvlRange: [40, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "chingling", weight: 3, lvlRange: [5, 30], tiers: ['uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "chimecho", weight: 1, lvlRange: [40, 50], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "shellder", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "cloyster", weight: 5, lvlRange: [25, 50], tiers: ['uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "krabby", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean, river'] },
    { pokemon: "kingler", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river'] },
    { pokemon: "horsea", weight: 25, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "seadra", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "goldeen", weight: 25, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "seaking", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "staryu", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river'] },
    { pokemon: "starmie", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river'] },
    { pokemon: "magikarp", weight: 80, lvlRange: [3, 7], tiers: ['common'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "magikarp", weight: 30, lvlRange: [3, 7], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "magikarp", weight: 20, lvlRange: [3, 7], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "magikarp", weight: 10, lvlRange: [3, 7], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "gyarados", weight: 2, lvlRange: [20, 40], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn', 'winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "lapras", weight: 1, lvlRange: [30, 50], tiers: ['rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "dratini", weight: 1, lvlRange: [5, 30], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "dragonair", weight: 0.5, lvlRange: [30, 50], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "totodile", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "croconaw", weight: .75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "feraligatr", weight: .25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "clobbopus", weight: 10, lvlRange: [3, 28], tiers: ['uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "grapploct", weight: 5, lvlRange: [35, 48], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "chinchou", weight: 10, lvlRange: [10, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "lanturn", weight: 5, lvlRange: [25, 40], tiers: ['uncommon', 'rare'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "politoed", weight: 10, lvlRange: [41, 50], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "wooper", weight: 25, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer'], waterTypes: ['fresh', 'river'] },
    { pokemon: "wooper", weight: 25, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['autumn', 'winter'], waterTypes: ['fresh', 'river'], variant: ['paldean'] },
    { pokemon: "quagsire", weight: 5, lvlRange: [20, 40], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer'], waterTypes: ['fresh', 'river'] },
    { pokemon: "clodsire", weight: 5, lvlRange: [20, 40], tiers: ['uncommon', 'rare'], seasons: ['autumn', 'winter'], waterTypes: ['fresh', 'river'] },
    { pokemon: "slowking", weight: 1, lvlRange: [35, 50], tiers: ['rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "slowking", weight: 1, lvlRange: [35, 50], tiers: ['rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['fresh', 'river'], variant: ['galarian'] },
    { pokemon: "qwilfish", weight: 15, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "qwilfish", weight: 15, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'], variant: ['hisuian'] },
    { pokemon: "shuckle", weight: 20, lvlRange: [5, 50], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer'], waterTypes: ['river', 'fresh'] },
    { pokemon: "corsola", weight: 20, lvlRange: [15, 40], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "corsola", weight: 20, lvlRange: [15, 39], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean'], variant: ['galarian'] },
    { pokemon: "cursola", weight: 20, lvlRange: [39, 70], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "remoraid", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "octillery", weight: 5, lvlRange: [25, 50], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "mantine", weight: 15, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "kingdra", weight: 1, lvlRange: [40, 50], tiers: ['rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "mudkip", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "marshtomp", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "swampert", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "lotad", weight: 25, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "lombre", weight: 10, lvlRange: [15, 30], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "ludicolo", weight: 2, lvlRange: [30, 50], tiers: ['rare', 'epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "carvanha", weight: 20, lvlRange: [5, 30], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "sharpedo", weight: 10, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "wailmer", weight: 20, lvlRange: [15, 25], tiers: ['common', 'uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "wailord", weight: 2, lvlRange: [40, 50], tiers: ['rare', 'epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "barboach", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "whiscash", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "barboach", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "tympole", weight: 1, lvlRange: [5, 10], tiers: ['common'], seasons: ['autumn', 'winter'], waterTypes: ['river'] },
    { pokemon: "palpitoad", weight: 5, lvlRange: [10, 28], tiers: ['uncommon'], seasons: ['autumn', 'winter'], waterTypes: ['river'] },
    { pokemon: "seismitoad", weight: 3, lvlRange: [30, 50], tiers: ['rare', 'epic'], seasons: ['autumn', 'winter'], waterTypes: ['river'] },
    { pokemon: "corphish", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "crawdaunt", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "feebas", weight: 2, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "milotic", weight: 0.25, lvlRange: [15, 50], tiers: ['epic'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "stunfisk", weight: 15, lvlRange: [3, 7], tiers: ['common'], seasons: ['spring', 'summer'], waterTypes: ['river', 'fresh'] },
    { pokemon: "stunfisk", weight: 15, lvlRange: [3, 7], tiers: ['common', 'uncommon'], seasons: ['autumn', 'winter'], waterTypes: ['river', 'fresh'], variant: ['galarian'] },
    { pokemon: "spheal", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "sphealeo", weight: 10, lvlRange: [30, 40], tiers: ['uncommon', 'rare'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "walrein", weight: 1, lvlRange: [40, 50], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "tynamo", weight: 20, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "eelektrik", weight: 10, lvlRange: [30, 40], tiers: ['uncommon', 'rare'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "eelektross", weight: 1, lvlRange: [40, 50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "wimpod", weight: 13, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "golisopod", weight: 5, lvlRange: [30, 40], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "clamperl", weight: 15, lvlRange: [10, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "huntail", weight: 5, lvlRange: [30, 40], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "gorebyss", weight: 5, lvlRange: [30, 40], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "relicanth", weight: 2, lvlRange: [20, 40], tiers: ['uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "luvdisc", weight: 10, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'], seasons: ['summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "piplup", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "prinplup", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "empoleon", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "buizel", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "floatzel", weight: 5, lvlRange: [25, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "shellos", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "gastrodon", weight: 2, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "finneon", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "lumineon", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "mantyke", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "oshawott", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "dewott", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "samurott", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'] },
    { pokemon: "samurott", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'fresh'], variant: ['hisuian'] },
    { pokemon: "basculin", weight: 20, lvlRange: [5, 20], tiers: ['common'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh'] },
    { pokemon: "basculegion", weight: 4, lvlRange: [5, 20], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh'] },
    { pokemon: "frillish", weight: 10, lvlRange: [10, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "jellicent", weight: 5, lvlRange: [40, 50], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "alomomola", weight: 5, lvlRange: [20, 40], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "froakie", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "frogadier", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "greninja", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "binacle", weight: 5, lvlRange: [5, 30], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "barbaracle", weight: 2, lvlRange: [30, 50], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "skrelp", weight: 10, lvlRange: [5, 30], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "dragalge", weight: 5, lvlRange: [5, 30], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "clauncher", weight: 10, lvlRange: [5, 30], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "clawitzer", weight: 2, lvlRange: [5, 30], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "goomy", weight: 2, lvlRange: [5, 30], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "sliggo", weight: 1, lvlRange: [40, 45], tiers: ['rare', 'epic'], seasons: ['spring', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "sliggo", weight: 1, lvlRange: [40, 45], tiers: ['rare', 'epic'], seasons: ['autumn', 'winter'], waterTypes: ['ocean'], variant: ['hisuian'] },
    { pokemon: "bergmite", weight: 5, lvlRange: [5, 30], tiers: ['uncommon'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "popplio", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "brionne", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "primarina", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['summer'], waterTypes: ['ocean', 'river'] },
    { pokemon: "wishiwashi", weight: 15, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "mareanie", weight: 5, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "toxapex", weight: 2, lvlRange: [25, 50], tiers: ['uncommon', 'rare'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "dewpider", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "araquanid", weight: 5, lvlRange: [25, 40], tiers: ['uncommon', 'rare'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "pyukumuku", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "bruxish", weight: 1, lvlRange: [5, 20], tiers: ['epic'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "dhelmise", weight: 10, lvlRange: [5, 20], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "sobble", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['fresh'] },
    { pokemon: "drizzile", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['fresh'] },
    { pokemon: "inteleon", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['fresh'] },
    { pokemon: "arrokuda", weight: 15, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "barraskewda", weight: 10, lvlRange: [26, 49], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "pincurchin", weight: 10, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['spring', 'autumn', 'summer'], waterTypes: ['ocean'] },
    { pokemon: "eiscue", weight: 10, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "snorunt", weight: 10, lvlRange: [5, 30], tiers: ['uncommon', 'rare'], seasons: ['winter'], waterTypes: ['fresh'] },
    { pokemon: "klawf", weight: 1, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "klawf", weight: 1, lvlRange: [30, 70], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean', 'river', 'fresh'] },
    { pokemon: "darumaka", weight: 3, lvlRange: [5, 30], tiers: ['uncommon', 'rare'], seasons: ['autumn', 'winter'], waterTypes: ['fresh'], variant: ['galarian'] },
    { pokemon: "darmanitan", weight: 1, lvlRange: [30, 48], tiers: ['rare', 'epic'], seasons: ['autumn', 'winter'], waterTypes: ['fresh'], variant: ['galarian'] },
    { pokemon: "inkay", weight: 6, lvlRange: [5, 30], tiers: ['uncommon', 'rare'], seasons: ['autumn', 'winter'], waterTypes: ['ocean'] },
    { pokemon: "malamar", weight: 3, lvlRange: [30, 48], tiers: ['rare', 'epic'], seasons: ['autumn', 'winter'], waterTypes: ['ocean'] },
    { pokemon: "bergmite", weight: 14, lvlRange: [5, 30], tiers: ['common', 'uncommon'], seasons: ['winter'], waterTypes: ['ocean', 'river'] },
    { pokemon: "avalugg", weight: 7, lvlRange: [37, 51], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean', 'river'] },
    { pokemon: "avalugg", weight: 3, lvlRange: [37, 51], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring', 'winter'], waterTypes: ['ocean', 'river'], variant: ['hisuian'] },
    { pokemon: "dreepy", weight: 1, lvlRange: [5, 30], tiers: ['rare', 'epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "quaxly", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "quaxwell", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "quaquaval", weight: 0.25, lvlRange: [16, 35], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['fresh', 'river'] },
    { pokemon: "finizen", weight: 5, lvlRange: [5, 35], tiers: ['common', 'uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['river', 'ocean'] },
    { pokemon: "palafin", weight: 2, lvlRange: [40, 50], tiers: ['epic'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean', 'river'] },
    { pokemon: "veluza", weight: 15, lvlRange: [20, 40], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "tatsugiri", weight: 15, lvlRange: [20, 30], tiers: ['uncommon'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    { pokemon: "dondozo", weight: 2, lvlRange: [30, 40], tiers: ['rare'], seasons: ['spring', 'summer', 'autumn'], waterTypes: ['ocean'] },
    // Magikarp Jump Variants
    { pokemon: "magikarp", variant: ["magikarp_jump=calico-orange-white"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=calico-white-orange"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=calico-orange-white-black"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['spring'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=orange-forehead"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=orange-mask"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['spring'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=orange-gold"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['spring'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=pink-two-tone"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['spring'], waterTypes: ['fresh'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=pink-orca"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['spring'], waterTypes: ['fresh'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=pink-dapples"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['spring'], waterTypes: ['fresh'] },

    { pokemon: "magikarp", variant: ["magikarp_jump=orange-two-tone"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=orange-orange-orca"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=orange-dapples"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['summer'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=blue-saucy"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=blue-raindrops"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=apricot-zebra"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=apricot-stripes"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['summer'], waterTypes: ['fresh'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=apricot-tiger"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['summer'], waterTypes: ['fresh'] },

    { pokemon: "magikarp", variant: ["magikarp_jump=brown-zebra"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['autumn'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=brown-stripes"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=brown-tiger"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['autumn'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=purple-bubbles"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=purple-patches"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=purple-diamonds"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['autumn'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=violet-saucy"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['autumn'], waterTypes: ['fresh'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=violet-raindrops"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['autumn'], waterTypes: ['fresh'] },

    { pokemon: "magikarp", variant: ["magikarp_jump=gray-bubbles"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=gray-patches"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=gray-diamonds"], weight: 1, lvlRange: [3, 7], tiers: ['epic'], seasons: ['winter'], waterTypes: ['river'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=black-forehead"], weight: 1, lvlRange: [3, 7], tiers: ['rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=black-mask"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['ocean'] },
    { pokemon: "magikarp", variant: ["magikarp_jump=skelly"], weight: 1, lvlRange: [3, 7], tiers: ['uncommon', 'rare', 'epic'], seasons: ['winter'], waterTypes: ['fresh'] },
]

global.cobblemonNetherFishPool = [
    { pokemon: "charmander", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "charmeleon", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "charizard", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "growlithe", weight: 5, lvlRange: [5, 35], tiers: ['common', 'uncommon'] },
    { pokemon: "arcanine", weight: 0.5, lvlRange: [35, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "ponyta", weight: 5, lvlRange: [5, 35], tiers: ['common', 'uncommon'] },
    { pokemon: "rapidash", weight: 0.5, lvlRange: [25, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "magby", weight: 10, lvlRange: [5, 15], tiers: ['common', 'uncommon'] },
    { pokemon: "mahgmar", weight: 5, lvlRange: [16, 30], tiers: ['common', 'uncommon'] },
    { pokemon: "magmortar", weight: 2, lvlRange: [35, 50], tiers: ['rare'] },
    { pokemon: "flareon", weight: 5, lvlRange: [5, 35], tiers: ['uncommon', 'rare'] },
    { pokemon: "cyndaquil", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "quilava", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "typhlosion", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "slugma", weight: 25, lvlRange: [5, 30], tiers: ['common', 'uncommon', 'rare'] },
    { pokemon: "magcargo", weight: 5, lvlRange: [36, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "torchic", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "combusken", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "blaziken", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "numel", weight: 25, lvlRange: [5, 30], tiers: ['common', 'uncommon'] },
    { pokemon: "camerupt", weight: 0.25, lvlRange: [36, 50], tiers: ['rare', 'epic'] },
    { pokemon: "torkoal", weight: 5, lvlRange: [5, 30], tiers: ['rare', 'uncommon'] },
    { pokemon: "chimchar", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "monferno", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "infernape", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "tepig", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "pignite", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "emboar", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "litwick", weight: 10, lvlRange: [5, 40], tiers: ['uncommon', 'common'] },
    { pokemon: "lampent", weight: 5, lvlRange: [41, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "chandelure", weight: 2, lvlRange: [42, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "heatmor", weight: 10, lvlRange: [5, 50], tiers: ['uncommon', 'common'] },
    { pokemon: "larvesta", weight: 10, lvlRange: [5, 50], tiers: ['uncommon', 'common'] },
    { pokemon: "volcarona", weight: 5, lvlRange: [50, 60], tiers: ['rare', 'epic'] },
    { pokemon: "fennekin", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "braixen", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "delphox", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "litten", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "torracat", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "incineroar", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "salandit", weight: 5, lvlRange: [5, 30], tiers: ['common', 'uncommon'], gender: ['male'] },
    { pokemon: "salandit", weight: 0.5, lvlRange: [5, 30], tiers: ['common', 'uncommon'], gender: ['female'] },
    { pokemon: "salazzle", weight: 0.5, lvlRange: [33, 50], tiers: ['rare'], gender: ['female'] },
    { pokemon: "turtonator", weight: 2, lvlRange: [42, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "scorbunny", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "raboot", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "cinderace", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "sizzlipede", weight: 25, lvlRange: [5, 25], tiers: ['common', 'uncommon'] },
    { pokemon: "centiskorch", weight: 5, lvlRange: [30, 50], tiers: ['uncommon', 'rare'] },
    { pokemon: "fuecoco", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "crocalor", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "skeledirge", weight: 0.25, lvlRange: [36, 50], tiers: ['epic'] },
    { pokemon: "charcadet", weight: 2, lvlRange: [5, 15], tiers: ['rare', 'epic'] },
    { pokemon: "ceruledge", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] },
    { pokemon: "armarouge", weight: 0.75, lvlRange: [16, 35], tiers: ['epic'] }
]