#How many menu items are required to open your cafe, per star + 1. Has a very large impact on difficulty!
#Range: 0 ~ 5
menu_size_per_star = 3
#The minimum seconds it can take for a customer to spawn at max reputation. Every star of reputation adds 20% of this value. For example, if its set to 20 seconds, these are the times per star: 400 | 320 | 240 | 160 | 80 | 20,
#Range: 4 ~ 4096
customer_spawn_interval = 30
#Chance an additional customer is added to the currently spawning group of customers. Repeats until a roll is failed or 4 customers are spawned/
#Range: 0.0 ~ 1.0
group_customer_chance = 0.5
#How long a customer will wait for their order, in ticks.
#Range: > 20
customer_wait_time = 1000
#How long it takes a customer to put in their order, in ticks.
#Range: > 20
customer_order_time = 200
#List of Minecraft usernames whose skins will be used for spawning customers.
customer_usernames = ["unnecessarymb", "ZephiraZ", "LocTheDoor", "Navia", "Tilles", "noodlescript", "kanlamari", "witchd", "Chakyl", "Nitbe", "_KingKarma_", "Mimsy34", "meepr_dib", "stillweighting", "MattTheMeow", "JexsamVT", "ProvidenceDaemon", "Irenaiad", "Tumbly", "", "MHF_Steve", "MHF_Alex", "MHF_Herobrine", "MHF_Chicken", "MHF_Pig", "MHF_Sheep", "MHF_Squid", "MHF_Villager", "MHF_Ocelot", "MHF_Blaze", "MHF_CaveSpider", "MHF_Enderman", "MHF_Ghast", "MHF_Golem", "MHF_LavaSlime", "MHF_PigZombie", "MHF_Skeleton", "MHF_Spider", "MHF_Witch", "MHF_Cake", "MHF_Chest", "MHF_OakLog", "MHF_Present1", "MHF_Present2", "MHF_Pumpkin", "MHF_TNT", "MHF_TNT2", "MHF_ArrowUp", "MHF_ArrowDown", "MHF_ArrowLeft", "MHF_ArrowRight", "MHF_Exclamation", "MHF_Question"]
#The item to use as a 1 denomination of currency (e.g.: minecraft:emerald)
currency_1 = "numismatics:spur"
#The item to use as a 8 denomination of currency (e.g.: minecraft:emerald)
currency_8 = "numismatics:bevel"
#The item to use as a 16 denomination of currency (e.g.: minecraft:emerald)
currency_16 = "numismatics:sprocket"
#The item to use as a 64 denomination of currency (e.g.: minecraft:diamond)
currency_64 = "numismatics:cog"
#The item to use as a 512 denomination of currency (e.g.: minecraft:emerald)
currency_512 = "numismatics:crown"
#The item to use as a 4096 denomination of currency (e.g.: minecraft:emerald)
currency_4096 = "numismatics:sun"
#Requires KubeJs and Quality Food. The stage name with the following impact: Quality impacts of non-fish prices are doubled. Can be added to the player using the command e.g, /kubejs stages add playerName the_quality_of_the_earth
quality_bonus_stage = "the_quality_of_the_earth"
#Requires KubeJs. The stage name with the following impact: Items with the tag cozy_cafe:pickles are worth 100% more. Can be added to the player using the command e.g, /kubejs stages add playerName brine_and_punishment
pickle_bonus_stage = "brine_and_punishment"
#Allows customers to pay to player's bank account directly if Create Numismatics Utils is installed. Set to false if you don't want that to happen.
numismatics_utils_payment = true
#Chance a customer orders a dessert, if the menu has any.
#Range: 0.0 ~ 1.0
dessert_chance = 0.4
#When enabled, limits cafe opening to once per Minecraft day.
daily_limit = true
#When enabled, main dishes that aren't in bowls will need to be plated using a Plating Station before serving.
plating_required = true
#When enabled, items from all mods will be registered as menu items if they're edible and do not have the tag cozycafe:not_served. Turn off if you want more control over the menu.
dynamic_menu_items = false

