#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Mar 28 14:58:42 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + Clrwl_1.0.0.zip
enableShaders=true
